Repository front-end-by-rimantas/20-grupe-portfolio-personal, pull requests merged in 2021-01, with the labels that each got.

#36 Create services section #4
  css/components/services.css
  index.html
Labels: CSS

#51 Create numbers section #5
  css/components/results.css
  css/components/services.css
  index.html
Labels: CSS

#70 logos
  css/components/logos.css
  img/logos1.webp
  img/logos2.webp
  img/logos3.webp
  img/logos4.webp
  img/logos5.webp
  index.html
Labels: CSS: responsive, HTML

#75 Render services #40
  index.html
  js/components/services/findIfValidSelector.js
  js/components/services/isValidServiceItem.js
  js/components/services/isValidServices.js
  js/components/services/renderServices.js
  js/data/servicesData.js
  js/home-main.js
Labels: JS

#84 add padding-bottom for services section
  css/components/services.css
Labels: Type: enhancement

#83 Render results
  css/components/results.css
  index.html
  js/components/results/Results.js
  js/components/results/isValidResultItem.js
  js/components/results/renderResults.js
  js/data/resultsData.js
  js/home-main.js
Labels: JS

#89 render plans
  css/components/plans.css
  index.html
  js/components/plans/Plans.js
  js/components/plans/findIfValidPlansSelector.js
  js/components/plans/isValidPlanItem.js
  js/components/plans/isValidPrices.js
  js/components/plans/renderPlanPrices.js
  js/data/planPricesData.js
  js/home-main.js
Labels: JS

#87 render socials
  index.html
  js/components/socials/findIfValidSelector.js
  js/components/socials/isValidSocialItem.js
  js/components/socials/isValidSocials.js
  js/components/socials/renderSocials.js
  js/data/socialsData.js
  js/home-main.js
Labels: JS

#96 make email required
  index.html
Labels: Type: enhancement

#104 h2 fix in about me
  css/components/about.css
  index.html
Labels: HTML

#98 add links in main menu to sections
  css/components/plans.css
  index.html
Labels: HTML
